name: Example

options:
  bundleIdPrefix: dev.jano.coordinator
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    IPHONEOS_DEPLOYMENT_TARGET: 15.4
    DEVELOPMENT_TEAM: PPSF6CNP8Q

packages:
 
    Coordinator:
      path: ..

targets:

  Example:
    dependencies:
      - package: Coordinator
    platform: iOS
    properties:
      UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
      UILaunchStoryboardName: LaunchScreen
    scheme:
      testTargets:
        - ExampleTests
    settings:
      INFOPLIST_FILE: targets/main/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: "dev.jano.coordinator.example"
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
      PRODUCT_NAME: Example
    sources:
      - sources/main
      - targets/main/Info.plist
    type: application
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint

  ExampleTests:
    dependencies:
      - package: Coordinator
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.coordinator.tests
      TEST_HOST:
    sources:
      - sources/uitests
    type: bundle.ui-testing
