name: Coordinator

options:
  bundleIdPrefix: dev.jano.coordinator
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:

 Coordinator:
   platform: iOS
   settings:
     CURRENT_PROJECT_VERSION: 1
     INFOPLIST_FILE: targets/main/Info.plist
     IPHONEOS_DEPLOYMENT_TARGET: 15.4
     PRODUCT_BUNDLE_IDENTIFIER: dev.jano.coordinator
     PRODUCT_NAME: Coordinator
   sources: 
      - sources/main
   type: framework
